#pragma once
#include <cstdint>
#include <vector>
using namespace std;
namespace _ecs {
	using id_type = uint8_t;
	using Dish = uint8_t;
	using Ingredient = uint8_t;
	const uint8_t NUM_DISH = 23;
	const uint8_t NUM_ING= 23; //n de ing del market
	const uint8_t NUM_MEAT_DISH = 5;
	enum _dish_id : id_type {
		FRIED_EGG,
		BREAD,
		MARMELADE,
		GARLIC_BREAD,
		FRENCH_FRIES,
		PANCAKE,
		STRAWBERRY_CAKE,
		CHOCOLATE_CAKE,
		RASPBERRY_CAKE,
		COOKIES,
		OMELETTE,
		APPLE_PIE,
		CHEESECAKE,
		BURRITO,
		PUREE,
		ICE_CREAM,
		NACHOS,
		HOTDOG,
		SANDWICH,
		SUSHI,
		CURRY_RICE,
		PIZZA,
		ROASTED_CHICKEN,
		STEAK,
		MEATBALLS,
		SPAGHETTI,
		HAMBURGER,
		RAMEN,
		NONE_DISH
	};
	enum _ingredients_id : id_type {
		FLOUR=29,
		EGG,
		POTATO,
		CHOCOLATE,
		LETTUCE,
		CORN,
		STRAWBERRY,
		CARROT,
		GARLIC,
		MILK,
		RICE,
		TOMATO,
		APPLE,
		BUTTER,
		RASPBERRY,
		MUSTARD,
		NOODLES,
		CURRY,
		CHEESE,
		SAUSAGE,
		CHICKEN,
		PRAWN,
		SALMON,
		MEAT,
		NONE_ING
	};

	struct DishInfo {
		_dish_id id;
		vector<_ingredients_id>ingredients;
		float cookingTime;
		int price;
	};

	struct IngInfo {
		_ingredients_id id;
		int price;
	};

	static IngInfo MarketIngs[NUM_ING] = {
		{FLOUR,1},
		{EGG,1},
		{POTATO,1},
		{CHOCOLATE,2},
		{LETTUCE,2},
		{CORN,2},
		{STRAWBERRY,2},
		{CARROT,2},
		{GARLIC,2},
		{MILK,2},
		{RICE,2},
		{TOMATO,3} ,
		{APPLE,2},
		{BUTTER,3},
		{RASPBERRY,3},
		{MUSTARD,3},
		{NOODLES,3},
		{CURRY,3},
		{CHEESE,4},
		{SAUSAGE,5},
		{CHICKEN,6},
		{PRAWN,7},
		{SALMON,8}
	};
	static DishInfo Dishes[NUM_DISH] = {
		{FRIED_EGG,{EGG},0.5,4},
		{BREAD,{FLOUR},0.7,4},
		{MARMELADE,{FLOUR,RASPBERRY},1,8},
		{GARLIC_BREAD,{FLOUR,GARLIC},0.7,7},
		{FRENCH_FRIES,{POTATO,TOMATO},1,8},
		{PANCAKE,{FLOUR,EGG,MILK},1.5,8},
		{STRAWBERRY_CAKE,{FLOUR,EGG,STRAWBERRY},2.5,9},
		{CHOCOLATE_CAKE,{FLOUR,EGG,CHOCOLATE},2.5,9},
		{RASPBERRY_CAKE,{FLOUR,EGG,RASPBERRY},2,10},
		{COOKIES,{FLOUR,CHOCOLATE,BUTTER},1.7,11},
		{OMELETTE,{FLOUR,EGG,CORN,BUTTER,},2,14},
		{APPLE_PIE,{FLOUR,EGG,APPLE},2.5,10},
		{CHEESECAKE,{FLOUR,EGG,CHEESE},2.5,12},
		{BURRITO,{FLOUR,LETTUCE,RICE},3,11},
		{PUREE,{POTATO,CARROT,GARLIC},3.5,11},
		{ICE_CREAM,{CHOCOLATE,STRAWBERRY,MILK,RASPBERRY},2.5,17},
		{NACHOS,{FLOUR,CORN,MUSTARD},3,16},
		{HOTDOG,{FLOUR,MUSTARD,SAUSAGE},2.7,19},
		{SANDWICH,{FLOUR,LETTUCE,SALMON},1,20},
		{SUSHI,{RICE,SALMON},3.7,21},
		{CURRY_RICE,{POTATO,GARLIC,RICE,CURRY},3,22},
		{PIZZA,{FLOUR,CHEESE,SAUSAGE},2,25},
		{ROASTED_CHICKEN,{CARROT,TOMATO,CHICKEN},6,28}
	};

	static DishInfo MeatDishes[NUM_MEAT_DISH] = {
		{STEAK,{CARROT,MEAT},4,15},
		{MEATBALLS,{FLOUR,CURRY,MEAT},5.5,18},
		{SPAGHETTI,{TOMATO,NOODLES,MEAT},5,20},
		{HAMBURGER,{FLOUR,LETTUCE,TOMATO,CHEESE,MEAT},6.5,30},
		{RAMEN,{EGG,GARLIC,NOODLES,PRAWN,MEAT},7,38}
	};

};